name: testhive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  flutter_foreground_task: ^8.10.2
  flutter_background_service: ^5.0.10
  workmanager: ^0.5.2
  flutter_local_notifications: ^17.2.3
  intl: ^0.19.0
  firebase_database: ^11.1.4
  fl_chart: ^0.69.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
